In [2]:
# Given  a 2D numpy array and perform opertaions: range,max,min,sum
import numpy as np

matrix = np.array([[6, 1, 1],
                   [4, -2, 5],
                   [2, 8, 7]])

max_val = np.max(matrix)
min_val = np.min(matrix)
range_val = np.ptp(matrix)
sum_val = np.sum(matrix)
determinant = np.linalg.det(matrix)
inverse = np.linalg.inv(matrix)
eigenvalues = np.linalg.eigvals(matrix)

print(f"Matrix:\n{matrix}")
print(f"Max: {max_val}, Min: {min_val}, Range: {range_val}, Sum: {sum_val}")
print(f"Determinant: {determinant}")
print(f"Inverse:\n{inverse}")
print(f"Eigenvalues: {eigenvalues}")

Matrix:
[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
Max: 8, Min: -2, Range: 10, Sum: 32
Determinant: -306.0
Inverse:
[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]
Eigenvalues: [11.24862343  5.09285054 -5.34147398]
